name: quoted_string
description: String quoting/unquoting. Provides an extension on String with quote() and unquote() methods.
version: 0.1.1
repository: https://github.com/f3ath/dart-quoted-string

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.1
  cider: ^0.2.3
  test: ^1.21.1
  check_coverage: ^0.0.2

cider:
  link_template:
    tag: 'https://github.com/f3ath/dart-quoted-string/releases/tag/%tag%'
    diff: 'https://github.com/f3ath/dart-quoted-string/compare/%from%...%to%'
